# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Wander' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Wander
  pod 'FlickrKit'
	

  target 'WanderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WanderUITests' do
    # Pods for testing
  end

end
